### ISSUE TITLE
Please make an official telegram theme and post to @TelegramThemes

### ISSUE THREAD

**Issue by vKnmnn** [ristomatti/telegram-solarized-dark#3]
[tg://resolve?domain=TelegramThemes](url)
thank you!

**Comment by ristomatti** [comment]
@LordTaifleh I will look into this. I assume this is related to the new desktop version they released? I haven't had time to try it out yet but great to hear if it has support for custom themes!

**Comment by vKnmnn** [comment]
There already is at least one solarized dark theme, but it doesn't look as good as yours. it's just too much of the base02 background.

**Comment by ristomatti** [comment]
@LordTaifleh I noticed that one also. The whole reason why I've created this and several other Solarized inspired themes is that I don't like the blue background even though I love the color palette otherwise!

Anyway I gave this a shot today. I've uploaded the results to https://t.me/TelegramThemes. My usename is the same here and theme is called **Solarized Dark Grey v1**. Preview below. Let me know what you think!

![image](https://cloud.githubusercontent.com/assets/9029939/22185684/b4e2e30a-e0f2-11e6-8775-03bbee90bdfe.png)

**Comment by ristomatti** [comment]
I was really struggling if I should have picked the blackish background also to the chat list but the same property affected also the area above the chat list. If that was dark also then the header section over the chat should be made also. I'm not sure if that would look very good.

**Comment by ristomatti** [comment]
I resubmitted the theme through **@tthemebot** and it's now waiting for approval. Meanwhile you can find it from this repo: [Solarized Dark Grey v1 Theme for Telegram Desktop](https://github.com/ristomatti/telegram-solarized-dark/blob/master/dist/SolarizedDarkGrey-v1.tdesktop-theme?raw=true).

**Comment by ristomatti** [comment]
There's on updated version available now. I finally figured out how that theme bot should be used. Just type: `@tthemebot Solarized Dark Grey v2` and the bot should display the theme inline. Don't forget to rank if you like the time!

I'll close this issue but I'd still appreaciate feedback!

**Comment by vKnmnn** [comment]
Thank you, it looks great!
